import {
  MIN_VOTES, OFFSET_BUCKET, decide,
  type Fingerprint, type Identification, type Match,
} from "@chirp/core";
import postgres, { type Sql } from "postgres";
import { newSongId, type SongRow } from "./schema";

export const FINGERPRINT_CHUNK = 2000;

export const HEAVY_FLOOR = 32;

export const MAX_POSTINGS_PER_HASH = 512;

export const RANKED_LIMIT = 10;

export const CARRY_VOTE_FLOOR = 3;

export const CARRY_LIMIT = 50;

export type Db = Sql;

export function connect(url: string, max = 5): Db {
  return postgres(url, { max, fetch_types: false, onnotice: () => {} });
}

const array = (values: readonly number[]) => `{${values.join(",")}}`;

export const PG_SCHEMA = [
  `CREATE TABLE IF NOT EXISTS songs (
     id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     nano_id     text NOT NULL UNIQUE,
     title       text NOT NULL,
     artist      text NOT NULL,
     album       text,
     duration_s  real,
     frame_count int,
     source_url  text,
     attribution text,
     cover_url   text,
     youtube_id  text,
     source      text,
     source_id   text,
     isrc        text,
     created_at  bigint NOT NULL DEFAULT extract(epoch from now())::bigint
   )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS songs_source ON songs (source, source_id)`,
  `CREATE TABLE IF NOT EXISTS fingerprints (
     hash         int NOT NULL,
     song_id      int NOT NULL,
     anchor_frame int NOT NULL,
     PRIMARY KEY (hash, song_id, anchor_frame)
   )`,
  `CREATE INDEX IF NOT EXISTS fingerprints_song ON fingerprints (song_id)`,
  `CREATE TABLE IF NOT EXISTS hash_stats (
     hash     int PRIMARY KEY,
     postings int NOT NULL
   )`,
];

// One statement per identification: four round trips at ~47 ms would dominate
// the request, so ranking, song metadata and the histogram come back together.
const IDENTIFY = `
WITH q(hash, qframe) AS (
  SELECT * FROM unnest($1::int[], $2::int[])
),
kept AS (
  SELECT q.hash, q.qframe
  FROM q LEFT JOIN hash_stats hs ON hs.hash = q.hash
  WHERE COALESCE(hs.postings, 0) <= $3
),
tally AS (
  SELECT f.song_id,
         (f.anchor_frame - kept.qframe) / ${OFFSET_BUCKET} AS bucket,
         COUNT(*)::int AS votes
  FROM kept
  JOIN fingerprints f ON f.hash = kept.hash
  WHERE f.anchor_frame >= kept.qframe
  GROUP BY 1, 2
),
best AS (
  SELECT DISTINCT ON (song_id) song_id, bucket, votes
  FROM tally
  ORDER BY song_id, votes DESC
),
ranked AS (
  SELECT b.votes, b.bucket, s.*
  FROM best b JOIN songs s ON s.id = b.song_id
  WHERE b.votes >= $4
  ORDER BY b.votes DESC
  LIMIT $5
)
SELECT json_build_object(
  'candidates', COALESCE((SELECT json_agg(row_to_json(r) ORDER BY r.votes DESC) FROM ranked r), '[]'::json),
  'histogram',  COALESCE((SELECT json_agg(json_build_array(t.bucket, t.votes) ORDER BY t.bucket)
                          FROM tally t
                          WHERE t.song_id = (SELECT r.id FROM ranked r ORDER BY r.votes DESC LIMIT 1)), '[]'::json)
) AS result`;

export interface Candidate extends SongRow {
  votes: number;
  bucket: number;
}

export interface Ranking {
  candidates: Candidate[];
  histogram: [bucket: number, votes: number][];
}

export async function rank(
  db: Db, query: readonly Fingerprint[], floor = MIN_VOTES, limit = RANKED_LIMIT,
  cap = MAX_POSTINGS_PER_HASH,
): Promise<Ranking> {
  const [row] = await db.unsafe<{ result: Ranking }[]>(IDENTIFY, [
    array(query.map((p) => p.hash)),
    array(query.map((p) => p.frame)),
    cap,
    floor,
    limit,
  ]);
  return row!.result;
}

export async function identifyIn(
  db: Db, query: readonly Fingerprint[], cap = MAX_POSTINGS_PER_HASH,
): Promise<Identification | null> {
  return decide(asMatches((await rank(db, query, MIN_VOTES, RANKED_LIMIT, cap)).candidates));
}

export const asMatches = (candidates: readonly Candidate[]): Match[] =>
  candidates.map((c) => ({ songId: c.id, offsetBucket: c.bucket, votes: c.votes }));

export interface SongInput {
  title: string;
  artist: string;
  album?: string | null;
  duration_s?: number | null;
  frame_count?: number | null;
  source_url?: string | null;
  attribution?: string | null;
  cover_url?: string | null;
  youtube_id?: string | null;
  source?: string | null;
  source_id?: string | null;
}

export async function insertSong(db: Db, song: SongInput): Promise<{ id: number; nanoId: string }> {
  const [row] = await db<{ id: number; nano_id: string }[]>`
    INSERT INTO songs (nano_id, title, artist, album, duration_s, frame_count,
                       source_url, attribution, cover_url, youtube_id, source, source_id)
    VALUES (${newSongId()}, ${song.title}, ${song.artist}, ${song.album ?? null},
            ${song.duration_s ?? null}, ${song.frame_count ?? null}, ${song.source_url ?? null},
            ${song.attribution ?? null}, ${song.cover_url ?? null}, ${song.youtube_id ?? null},
            ${song.source ?? null}, ${song.source_id ?? null})
    RETURNING id, nano_id`;
  return { id: row!.id, nanoId: row!.nano_id };
}

const INSERT_CHUNK = 50_000;

export async function insertFingerprints(
  db: Db, songId: number, prints: readonly Fingerprint[],
): Promise<void> {
  for (let i = 0; i < prints.length; i += INSERT_CHUNK) {
    const chunk = prints.slice(i, i + INSERT_CHUNK);
    await db.unsafe(
      `INSERT INTO fingerprints (hash, song_id, anchor_frame)
       SELECT * FROM unnest($1::int[], $2::int[], $3::int[]) ON CONFLICT DO NOTHING`,
      [array(chunk.map((p) => p.hash)), array(chunk.map(() => songId)), array(chunk.map((p) => p.frame))],
    );
  }
}

export async function refreshHashStats(db: Db): Promise<number> {
  await db`TRUNCATE hash_stats`;
  await db`
    INSERT INTO hash_stats (hash, postings)
    SELECT hash, COUNT(*) FROM fingerprints GROUP BY hash HAVING COUNT(*) > ${HEAVY_FLOOR}`;
  const [row] = await db<{ n: number }[]>`SELECT COUNT(*)::int n FROM hash_stats`;
  return row!.n;
}

export const songById = async (db: Db, id: number): Promise<SongRow | null> => {
  const [row] = await db<SongRow[]>`SELECT * FROM songs WHERE id = ${id}`;
  return row ?? null;
};

export interface CatalogueRow extends SongRow {
  postings: number;
}

export const catalogue = (db: Db) =>
  db<CatalogueRow[]>`
    SELECT s.*, COALESCE(f.postings, 0)::int AS postings
    FROM songs s
    LEFT JOIN (SELECT song_id, COUNT(*)::int AS postings FROM fingerprints GROUP BY song_id) f
      ON f.song_id = s.id
    ORDER BY s.artist, s.title`;

export const findSongBySource = async (db: Db, source: string, sourceId: string, sourceUrl: string) => {
  const [row] = await db<{ id: number; title: string }[]>`
    SELECT id, title FROM songs
    WHERE (source = ${source} AND source_id = ${sourceId})
       OR (source_url IS NOT NULL AND source_url = ${sourceUrl})`;
  return row ?? null;
};
